version: "3"
services:
  monapp:
    build: .
    image: monimage
    depends_on:
      - redis
    ports:
      - "80:80"
    volumes:
      - static:/static
    networks:
      - monreseau
    environment:
      - NOM=les amis
  redis:
    image: redis
    volumes:
      - static:/static
    networks:
      - monreseau

networks:
  monreseau:
volumes:
  static:
